# base image
FROM flink:1.19-scala_2.12-java11

# Create Library Directory
RUN mkdir -p /opt/sql-client/lib

# Download connector libraries - making them available to the SQL Client at runtime
RUN wget -P /opt/sql-client/lib/  https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-kafka/3.2.0-1.19/flink-sql-connector-kafka-3.2.0-1.19.jar; \
    wget -P /opt/sql-client/lib/  https://repo1.maven.org/maven2/org/apache/flink/flink-json/1.19.0/flink-json-1.19.0.jar; 
